### ISSUE TITLE
Refactor ErrMissingField and similar error handling

### ISSUE THREAD

**Issue by mabdi3** [googleinterns/cloud-operations-api-mock#15]
~Following https://blog.golang.org/go1.13-errors, we want to refactor `ErrMissingField` as a struct, where we override the `Error()`, like so:~
```
func (err *MissingFieldError) Error() string {
	return fmt.Sprintf("request is missing required fields: %v",
		strings.Join(err.missingFields, ", "))
}
```

EDIT: ~Instead, we're going to try and handle errors more [_gracefully_](https://dave.cheney.net/2016/04/27/dont-just-check-errors-handle-them-gracefully).~ We're just going to keep the error handling the way it is now, and hide it to users of the api. See [here](https://golang.org/doc/go1.4#internalpackages). In addition, we can replace the string checking for determining errors with ID checking instead since string comparisons are very brittle. Issue linked [here](https://github.com/googleinterns/cloud-operations-api-mock/issues/22).

**Comment by the-ericwang35** [comment]
Closing this since we need to keep our errors as statuses for gRPC (see [here](https://cloud.google.com/apis/design/errors), and we're hiding them from the users now after https://github.com/googleinterns/cloud-operations-api-mock/pull/19. We should still figure out a better way of testing these errors (that's the only reason we're exporting the statuses anyways), which can be done in https://github.com/googleinterns/cloud-operations-api-mock/issues/22
